version: '3.8'
services:
  db:
    container_name: product-feedback-app-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_feedback
    ports:
      - '5440:5432'
volumes:
  db:
    driver: local
